#!/bin/bash
#PBS -N phmC-PH
#PBS -j oe
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=30,walltime=240:00:00,vmem=300gb
#PBS -m n
#PBS -d /work/phenotyprediction/data/phemale
#PBS -o /work/phenotyprediction/data/phemale/PH.out
#PBS -W group_list=phenotyprediction
#PBS -V

export EGGNOG_DATA_DIR=/work/phenotyprediction/data/data/databases
PATH=eggnog-mapper:/work/phenotyprediction/data/phemale/eggnog-mapper/eggnogmapper/bin:"$PATH"
python3 main.py 30